# CropDisease Main Configuration
Enable: true
Debug: true
PlaceSandUnderDeadbush: true

# Crop types
# <MATERIAL>: <alias>
Types:
  SUGAR_CANE_BLOCK: Sugarcane
  CROPS: Wheat
  PUMPKIN_STEM: Pumpkin
  MELON_STEM: Melon
  CARROT: Carrot
  POTATO: Potato
  NETHER_STALK: Netherwart

# Crop disease chances
# Chance 0 means 0% and 1 stands for 100%
# <alias>: <chance> [result MATERIAL]
Infect:
  Sugarcane: 0.2 DEAD_BUSH
  Wheat: 0.05
  Pumpkin: 0.06 DEAD_BUSH
  Melon: 0.06 DEAD_BUSH
  Carrot: 0.04
  Potato: 0.06
  Netherwart: 0.15