# CropDisease Main Configuration
Enabled: true

# Crop types
# MATERIAL_DATA: alias
Types:
  SUGAR_CANE_BLOCK: Sugarcane
  CROPS: Wheat
  PUMPKIN_STEM: Pumpkin
  MELON_STEM: Melon
  CARROT: Carrot
  POTATO: Potato
  NETHER_STALK: Netherwart

# Crop disease chances
# alias: chance (0 means 0% and 1 stands for 100%)
Chance:
  Sugarcane: 0.3
  Wheat: 0.2
  Pumpkin: 0.25
  Melon: 0.25
  Carrot: 0.2
  Potato: 0.1
  Netherwart: 0