# CropDisease Main Configuration
Enable: true
PlaceSandUnderDeadbush: true

# Crop types
# <MATERIAL>: <alias>
Types:
  SUGAR_CANE_BLOCK: Sugarcane
  CROPS: Wheat
  PUMPKIN: Pumpkin
  PUMPKIN_STEM: Pumpkin
  MELON: Melon
  MELON_STEM: Melon
  CARROT: Carrot
  POTATO: Potato
  NETHER_STALK: Netherwart

# Crop disease chances
# Chance 0 means 0% and 1 stands for 100%
# <alias>: <chance> [result MATERIAL]
Infect:
  Sugarcane: 0.2 DEAD_BUSH
  Wheat: 0.12
  Pumpkin: 0.14 DEAD_BUSH
  Melon: 0.14 DEAD_BUSH
  Carrot: 0.08
  Potato: 0.05
  Netherwart: 0.15
