name: CropDisease
version: 1.0
description: A simple plugin that calls crop diseases in Minecraft
author: jupiter1390
main: com.naver.jupiter1390.CropDisease

commands:
  cropdisease:
    description: Displays CropDisease plugin's information.
    aliases: [cd, crop]
    usage: Type /cropdisease help to see commands list.
    
permissions:
  cropdisease.reload:
    description: Allows to reload plugin configurations.
    default: op